UPCourt.Web/Controllers/NoticeCaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UPCourt.Entity;
using UPCourt.Web.Core;
using UPCourt.Web.Models;
using UPCourt.Web.Service.DataService;

namespace UPCourt.Web.Controllers
{
    public class NoticeCaseController : BaseMVCController
    {
        // GET: NoticeCase
        public ActionResult Index()
        {
            if (!IsValidPermission(rModel, PageName.NoticeToCase, PagePermissionType.CanView))
            {
                return RedirectToAction("Index", "Login");
            }
            NoticeCaseIndexMvcModel model = new NoticeCaseIndexMvcModel()
            {
                NoticeNo = string.Empty,
                NoticeFromDate = DateTime.Now.AddMonths(-1),
                NoticeToDate = DateTime.Now
            };

            var dbData = NoticeDataService.GetDetail(db)
                .Where(F => F.Status == Entity.NoticeStatus.Pending
                && F.NoticeDate >= model.NoticeFromDate
                && F.NoticeDate <= model.NoticeToDate)
                .OrderByDescending(i => i.NoticeDate)
                .ThenByDescending(F => F.NoticeNo).ToList();

            model.CaseStatuses = GetAllStatus();

            //model.CaseStatuses = AllStatuses
            //    .Select(i => new SelectListItem { Text = i.Name, Value = i.CaseStatusId.ToString(), Selected = i == AllStatuses.First() }).ToList();

            model.Notices = NoticeMvcModel.CopyFromEntityList(dbData, 0);
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(NoticeCaseIndexMvcModel model)
        {
            var dbData = NoticeDataService.GetDetail(db)
                .Where(F => F.Status == Entity.NoticeStatus.Pending
                && (model.NoticeNo == null || F.NoticeNo.Contains(model.NoticeNo))
                && (!model.NoticeFromDate.HasValue || F.NoticeDate.Value.Date >= model.NoticeFromDate.Value.Date)
                && (!model.NoticeToDate.HasValue || F.NoticeDate.Value.Date <= model.NoticeToDate.Value.Date)
                )
                .OrderByDescending(i => i.NoticeDate)
                .ThenByDescending(F => F.NoticeNo).ToList();
            model.CaseStatuses = GetAllStatus();
            model.Notices = NoticeMvcModel.CopyFromEntityList(dbData, 0);
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateCase(NoticeCaseIndexMvcModel model)
        {
            var Notice = NoticeDataService.GetDetail(db).FirstOrDefault(F => F.NoticeId == model.NoticeId);
            if (Notice.IsNull()) return RedirectToAction("Index");
            var TotalCases = CaseDataService.GetLite(db).ToList().Count;
            Case NewCase = new Case()
            {
                CaseId = Guid.NewGuid(),
                NoticeId = model.NoticeId,
                OrdinalNo = TotalCases + 1,
                PetitionNo = model.CaseNo.Trim(),
                CaseStatusId = model.CaseStatusId,
                Type = Notice.NoticeType,
                PetitionerId = Notice.PetitionerId,
                NoticeCounselorId = Notice.NoticeCounselorId,
                ModifyBy = AppUser.UserName
            };
            //Party and Respondents
            Notice.Parties.ToList().ForEach(F => F.CasePartyId = NewCase.CaseId);
            Notice.Respondents.ToList().ForEach(F => F.CaseRespondentId = NewCase.CaseId);
            Notice.BasicIndexs.ToList().ForEach(F => F.CaseId = NewCase.CaseId);

            Notice.Status = NoticeStatus.Accept;

            db.Cases.Add(NewCase);
            db.SaveChanges();
            return RedirectToAction("Create", new { id = NewCase.CaseId });
        }

        // GET: NoticeCase/Create
        public ActionResult Create(Guid id)
        {
            var model = new NewCaseHearingMvcModel();
            var modelCaseHearing = new CaseHearingMvcModel();
            var Case = CaseDataService.GetDetail(db).FirstOrDefault(F => F.CaseId == id);
            modelCaseHearing.Case = CaseMvcModel.CopyFromEntity(Case, 0);
            modelCaseHearing.CaseId = id;
            modelCaseHearing.Documents = new List<DocumentMvcModel>();
            model.Hearing = modelCaseHearing;
            return View(model);
        }

        // POST: NoticeCase/Create
        [HttpPost]
        public ActionResult Create(NewCaseHearingMvcModel model)
        {
            try
            {
                // TODO: Add insert logic here
                var uploadDocs = FileUploadCommon(rModel, Enumerable.Empty<Document>(), Enumerable.Empty<DocumentMvcModel>(), 1, 10, DocumentType.Any);
                if (!rModel.IsSuccess)
                {
                    DisplayMessage(MessageType.Error, rModel.Message, "File upload issue", "Failure");
                    return RedirectToAction("Create", new { id = model.Hearing.Case.CaseId });
                }
                Case dbCase = CaseDataService.GetDetail(db).FirstOrDefault(F => F.CaseId == model.Hearing.Case.CaseId);
                CaseHearing Hearing = dbCase.CaseHearings.FirstOrDefault();
                if (Hearing.IsNull())
                {
                    Hearing = new CaseHearing()
                    {
                        CaseHearingId = Guid.NewGuid(),
                        HearingDate = model.Hearing.HearingDate
                    };
                }
                Hearing.CaseId = model.Hearing.Case.CaseId;
                Hearing.NextHearingDate = model.Hearing.NextHearingDate;
                Hearing.ModifyBy = AppUser.UserName;
                Hearing.Documents = Hearing.Documents ?? new List<Document>();
                //Name = postedFile.FileName,
                //DocumentUrl = newFileInfo.Item3,
                //Size = postedFile.ContentLength,
                //DocumentId = Guid.NewGuid()
                foreach (var doc in uploadDocs)
                {
                    doc.CaseHearingId = Hearing.CaseHearingId;
                    doc.Name = model.Document.Name;
                    doc.Type = DocumentType.Any;
                    doc.EntityType = DocumentEntityType.CaseHearing;
                    //doc.Ordinal = 
                }

                return RedirectToAction("Create", new { id = model.Hearing.Case.CaseId });
            }
            catch
            {
                return View();
            }
        }

        List<SelectListItem> GetAllStatus()
        {
            var AllStatuses = CaseStatusDataService.GetLite(db).ToList();
            var CaseStatuses = new List<SelectListItem>();
            for (int i = 0; i < AllStatuses.Count; i++)
            {
                CaseStatuses.Add(new SelectListItem()
                {
                    Text = AllStatuses[i].Name,
                    Value = AllStatuses[i].CaseStatusId.ToString(),
                    Selected = AllStatuses[0].CaseStatusId == AllStatuses[i].CaseStatusId
                });
            }
            return CaseStatuses;
        }
    }
}

UPCourt.Web/Views/NoticeCase/Index.cshtml
@model UPCourt.Web.Models.NoticeCaseIndexMvcModel
@{
    ViewBag.Title = "Notice awating for case";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Notice awaiting for case</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item active">Awating Notice</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@using (Html.BeginForm("Index", "NoticeCase", FormMethod.Post, new { @class = "col-md-12" }))
{
    @Html.AntiForgeryToken()
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Search Notice</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    @Html.LabelFor(model => model.NoticeNo, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.NoticeNo, new { htmlAttributes = new { @class = "form-control", @placeholder = "Notice No" } })
                </div>
                <div class="col-2">
                    @Html.LabelFor(model => model.NoticeFromDate, htmlAttributes: new { @class = "control-label" })
                    <div class="input-group date" id="fromdate" data-target-input="nearest">
                        @Html.TextBoxFor(model => model.NoticeFromDate, "{0:dd-MMM-yyyy}", new { @class = "form-control datetimepicker-input", @data_target = "#fromdate", @placeholder = "dd-mm-yyyy" })
                        <div class="input-group-append" data-target="#fromdate" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    @Html.LabelFor(model => model.NoticeToDate, htmlAttributes: new { @class = "control-label" })
                    <div class="input-group date" id="todate" data-target-input="nearest">
                        @Html.TextBoxFor(model => model.NoticeToDate, "{0:dd-MMM-yyyy}", new { @class = "form-control datetimepicker-input", @data_target = "#todate", @placeholder = "dd-mm-yyyy" })
                        <div class="input-group-append" data-target="#todate" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <label>&nbsp;</label>
                    <button type="submit" class="btn btn-block btn-primary">
                        <i class="fas fa-search-plus"></i> Search
                    </button>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
}
<!-- /.card -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Notice No</th>
                            <th>Date</th>
                            <th>Type</th>
                            <th>Parties</th>
                            <th>Respondent</th>
                            <th>Case</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var Notice in Model.Notices)
                        {
                            <tr class="tr-class-2">
                                <td>@Notice.NoticeNo</td>
                                <td>@(Notice.NoticeDate.HasValue ? Notice.NoticeDate.Value.ToString("dd-MMM-yyyy") : string.Empty)</td>
                                <td>@Notice.NoticeType.ToString()</td>
                                <td>@String.Join(",", Notice.NoticeParties.Select(F => F.PartyName))</td>
                                <td>@String.Join(",", Notice.NoticeRespondent.Select(F => F.PartyName))</td>
                                <td>
                                    <!--
                                    <a class="btn btn-info btn-sm" href="@Url.Action("Create", "NoticeCase", new { id = Notice.NoticeId })">
                                        <i class="fas fa-file-alt"></i> Create Case
                                    </a>-->
                                    <Button class="btn btn-primary btn-sm" onclick="$('#NoticeId').val($(this).attr('notice'))" notice="@(Notice.NoticeId.ToString())" data-toggle="modal" data-target="#modal-Case" action="addcase">
                                        <i class="fas fa-file-alt"></i> Create Case
                                    </Button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.modal -->

@using (Html.BeginForm("CreateCase", "NoticeCase", FormMethod.Post))
{
    @Html.HiddenFor(model => model.NoticeId)
    @Html.AntiForgeryToken()
    <div class="modal fade" id="modal-Case">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <h4 class="modal-title">Provide Case No</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        @Html.LabelFor(model => model.CaseNo, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.CaseNo, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Case No", @required = "true" } })
                        @*@Html.ValidationMessageFor(model => model.CaseNo, "Please enter case no.", new { @class = "text-danger" })*@
                    </div>
                    <div class="row mb-2"></div>
                    <div class="row">
                        @Html.LabelFor(model => model.CaseStatusId, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(m => m.CaseStatusId, Model.CaseStatuses, new { @class = "form-control select", @required = "true" })
                        @*@Html.ValidationMessageFor(model => model.CaseStatusId, "Please select case status", new { @class = "text-danger" })*@
                    </div>
                </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">
                            <i class="fas fa-times-circle"></i> Close
                        </button>
                        <button type="submit" class="btn btn-primary">
                            <i class="fas fa-save"></i> Save Case No
                        </button>
                    </div>
                </div>
        </div>
    </div>
}

<!-- /.modal -->

@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/datatables/CustomDataTable.js")
    @Scripts.Render("~/Scripts/Court/NoticeCase.js")
}