UPCourt.Web/Controllers/CaseStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UPCourt.Entity;
using UPCourt.Web.Core;
using UPCourt.Web.Models;
using UPCourt.Web.Service.DataService;

namespace UPCourt.Web.Controllers
{
    public class CaseStatusController : BaseMVCController
    {
        // GET: CaseStatus
        public ActionResult Index()
        {
            var dbData = CaseStatusDataService.GetLite(db).OrderBy(i => i.Name).ToList();
            return View(CaseStatusMvcModel.CopyFromEntityList(dbData, 0));
        }

        // GET: CaseStatus/Details/5
        public ActionResult Details(Guid id)
        {
            var dbData = CaseStatusDataService.GetLite(db).Where(i => i.CaseStatusId == id).FirstOrDefault();
            if (dbData == null)
            {
                return RedirectToAction("Index");
            }
            return View(CaseStatusMvcModel.CopyFromEntity(dbData, 0));
        }

        // GET: CaseStatus/Create
        public ActionResult Create()
        {
            var model = new CaseStatusMvcModel();
            return View(model);
        }

        // POST: CaseStatus/Create
        [HttpPost]
        public ActionResult Create(CaseStatusMvcModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (!CommonForInsertUpdate(model))
            {
                return View(model);
            }
            //if (!IsValidPermission(rModel, PageName.UserRole, PagePermissionType.CanCreate))
            //{
            //    return rModel;
            //}
            CaseStatus tempCaseStatus = new CaseStatus();
            tempCaseStatus.CaseStatusId = Guid.NewGuid();
            InitializeData(tempCaseStatus, model);

            db.CaseStatuses.Add(tempCaseStatus);
            db.SaveChanges();
            SucessMessage = $"Case Status {tempCaseStatus.Name} created sucessfully";

            return RedirectToAction("Index");
        }

        // GET: CaseStatus/Edit/5
        public ActionResult Edit(Guid id)
        {
            var dbData = CaseStatusDataService.GetLite(db).Where(i => i.CaseStatusId == id).FirstOrDefault();
            if (dbData == null)
            {
                return RedirectToAction("Index");
            }
            return View(CaseStatusMvcModel.CopyFromEntity(dbData, 0));
        }

        // POST: CaseStatus/Edit/5
        [HttpPost]
        public ActionResult Edit(CaseStatusMvcModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var dbData = CaseStatusDataService.GetLite(db).Where(i => i.CaseStatusId == model.CaseStatusId).FirstOrDefault();
            if (dbData == null)
            {
                return RedirectToAction("Index");
            }
            if (!CommonForInsertUpdate(model))
            {
                return View(model);
            }
            InitializeData(dbData, model);

            db.SaveChanges();
            SucessMessage = $"Case Status {dbData.Name} update sucessfully";

            return RedirectToAction("Index");
        }

        private void InitializeData(CaseStatus tempCaseStatus, CaseStatusMvcModel model)
        {
            tempCaseStatus.Name = model.Name;
            tempCaseStatus.HexColorCode = model.HexColorCode;
            tempCaseStatus.Type = CaseStatusType.Normal;
            tempCaseStatus.ModifyBy = AppUser.UserName;
        }
        private bool CommonForInsertUpdate(CaseStatusMvcModel model)
        {
            var nameForCheck = model.Name.TrimX();
            var duplicateCheck = CaseStatusDataService.GetLite(db).FirstOrDefault(i => i.CaseStatusId != model.CaseStatusId && i.Name == nameForCheck);
            if (duplicateCheck != null)
            {
                ModelState.AddModelError(nameof(model.Name), "Case Status name already exists");
                return false;
            }
            return true;
        }
    }
}

UPCourt.Web/Views/CaseStatus/Create.cshtml
@model UPCourt.Web.Models.CaseStatusMvcModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Case-Status Create</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Case-Status Create</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- general form elements -->
@using (Html.BeginForm("Create", "CaseStatus", FormMethod.Post, new { @class = "col-md-12" }))
{
    @Html.HiddenFor(model => model.CaseStatusId)
    @Html.AntiForgeryToken()
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Case-Status</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                @*<div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "" }) <br />
                        @Html.EnumDropDownListFor(m => m.Type, "--Select--", new { @class = "form-control select2", @style = "width: 100%" })
                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.HexColorCode, htmlAttributes: new { @class = "control-label" })
                        <div class="input-group my-colorpicker2">
                            @Html.EditorFor(model => model.HexColorCode, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @required = "true" } })
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-square"></i></span>
                            </div>
                            @Html.ValidationMessageFor(model => model.HexColorCode, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
}
<!-- /.card -->
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}

UPCourt.Web/Views/CaseStatus/Details.cshtml
@model UPCourt.Web.Models.CaseStatusMvcModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Case Status Details</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Case Status Details</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<!-- general form elements -->
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Case Status</h3>
    </div>
    <form>
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @readonly = "readonly" } })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.HexColorCode, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.HexColorCode, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Description", @type = "text", @readonly = "readonly" } })

                </div>
            </div>
            @*<div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "" }) <br />
                    @Html.EnumDropDownListFor(m => m.Type, "--Select--", new { @class = "form-control select2", @style = "width: 100%", @disabled = "disabled" })
                </div>
            </div>*@
        </div>
        <div class="card-footer">
            <a href="@Url.Action("Index", "CaseStatus")" class="btn btn-primary">
                Back
            </a>
        </div>

    </form>
</div>
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}

UPCourt.Web/Views/CaseStatus/Edit.cshtml
@model UPCourt.Web.Models.CaseStatusMvcModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Case Status Edit</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Case Status Edit</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- general form elements -->
@using (Html.BeginForm("Edit", "CaseStatus", FormMethod.Post, new { @class = "col-md-12" }))
{
    @Html.HiddenFor(model => model.CaseStatusId)
    @Html.AntiForgeryToken()
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Case Status</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                @*<div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "" }) <br />
                        @Html.EnumDropDownListFor(m => m.Type, "--Select--", new { @class = "form-control select2", @style = "width: 100%" })
                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.HexColorCode, htmlAttributes: new { @class = "control-label" })
                        <div class="input-group my-colorpicker2">
                            @Html.EditorFor(model => model.HexColorCode, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @required = "true" } })
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-square"></i></span>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.HexColorCode, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
}
<!-- /.card -->
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}

UPCourt.Web/Views/CaseStatus/Index.cshtml
@model IEnumerable<UPCourt.Web.Models.CaseStatusMvcModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Case Status</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Case Status</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    @Html.ActionLink("Create", "Create", null, htmlAttributes: new { @class = "btn btn-block btn-success" })
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Hex Color Code</th>
                            <th>View</th>
                            <th>Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="tr-class-2">
                                <td>@item.Name</td>
                                <td>@item.HexColorCode</td>
                                @*<td>@item.Type</td>*@
                                <td class="project-actions text-center">
                                    <a class="btn btn-primary btn-sm" href="@Url.Action("Details", "CaseStatus", new { id = item.CaseStatusId })">
                                        <i class="fas fa-folder">
                                        </i>
                                        View
                                    </a>
                                </td>
                                <td>
                                    <a class="btn btn-info btn-sm" href="@Url.Action("Edit", "CaseStatus", new { id = item.CaseStatusId })">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Edit
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/datatables/CustomDataTable.js")
    @*@Scripts.Render("~/FrontEnd/plugins/datatables/js")*@
    @*@Scripts.Render("~/Scripts/Tables/Data")*@
}