UPCourt.Web/Controllers/GovermentDepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UPCourt.Entity;
using UPCourt.Web.Core;
using UPCourt.Web.Models;
using UPCourt.Web.Service.DataService;

namespace UPCourt.Web.Controllers
{
    public class GovermentDepartmentController : BaseMVCController
    {
        // GET: Department
        public ActionResult Index()
        {
            var dbData = GovermentDepartmentDataService.GetDetail(db).OrderBy(i => i.Name).ToList();
            /* GovernmentDepartmentAddressMvcModel GovernmentDepartmentAddressList = new GovernmentDepartmentAddressMvcModel();
             GovermentDepartmentMvcModel govermentDepartmentMvcModel = new GovermentDepartmentMvcModel();

              GovernmentDepartmentContactNoMvcModel GovernmentDepartmentContactNoList = new GovernmentDepartmentContactNoMvcModel();*/
            return View(GovermentDepartmentMvcModel.CopyFromEntityList(dbData, 0));
        }
        // GET: Department/Create
        public ActionResult Create()
        {

            InitilizeGovermentDepartment(null);

            var model = new GovermentDepartmentMvcModel();
            model.GovernmentDepartmentAddresses = new List<GovernmentDepartmentAddressMvcModel>();
            model.GovernmentDepartmentContactNos = new List<GovernmentDepartmentContactNoMvcModel>();
            model.GovernmentDepartmentContactNos.Add(new GovernmentDepartmentContactNoMvcModel());
            model.GovernmentDepartmentAddresses.Add(new GovernmentDepartmentAddressMvcModel());
            // model.GovernmentDepartmentContactNos = new List<GovernmentDepartmentContactNoMvcModel>();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(GovermentDepartmentMvcModel model)
        {
            // model.GovernmentDepartmentAddressList.Add(new GovernmentDepartmentAddressMvcModel());
            InitilizeGovermentDepartment(model.GovernmentDepartmentId);
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (!CommonForInsertUpdate(model))
            {
                return View(model);
            }

            GovernmentDepartment tempData = new GovernmentDepartment();
            tempData.GovernmentDepartmentId = Guid.NewGuid();
            tempData.Name = model.Name;
            tempData.Email = model.Email;
            tempData.Status = model.Status;
            tempData.IsDefault = model.IsDefault;
            tempData.POCName = model.POCName;
            tempData.POCContact = model.POCContact;
            tempData.ModifyBy = AppUser.UserName;
            tempData.HeadOffice = model.HeadOffice;
            tempData.GovernmentDepartmentAddresses = new List<GovernmentDepartmentAddress>();
            tempData.GovernmentDepartmentContactNos = new List<GovernmentDepartmentContactNo>();
            foreach (var item in model.GovernmentDepartmentContactNos)
            {
                if (!item.DeletePhone)
                {
                    GovernmentDepartmentContactNo governmentDepartmentContactNo = new GovernmentDepartmentContactNo();
                    governmentDepartmentContactNo.GovernmentDepartmentContactNoId = Guid.NewGuid();
                    governmentDepartmentContactNo.GovernmentDepartmentId = tempData.GovernmentDepartmentId;
                    governmentDepartmentContactNo.ContactNo = item.ContactNo;
                    governmentDepartmentContactNo.ModifyBy = AppUser.UserName;
                    db.GovernmentDepartmentContactNos.Add(governmentDepartmentContactNo);
                }
            }
            foreach (var item in model.GovernmentDepartmentAddresses)
            {
                if (!item.DeleteAddress)
                {
                    GovernmentDepartmentAddress tempGovernmentDepartmentAddress = new GovernmentDepartmentAddress();
                    tempGovernmentDepartmentAddress.GovernmentDepartmentAddressId = Guid.NewGuid();
                    tempGovernmentDepartmentAddress.GovernmentDepartmentId = tempData.GovernmentDepartmentId;
                    tempGovernmentDepartmentAddress.Address = item.Address;
                    tempGovernmentDepartmentAddress.IsHeadOfficeAddress = item.IsHeadOfficeAddress;
                    tempGovernmentDepartmentAddress.ModifyBy = AppUser.UserName;
                    db.GovernmentDepartmentAddresses.Add(tempGovernmentDepartmentAddress);
                }
            }
            db.GovernmentDepartments.Add(tempData);
            db.SaveChanges();
            SucessMessage = $"Govt. Department {tempData.Name} Created sucessfully";

            return RedirectToAction("Index");
        }
        public ActionResult Edit(Guid id)
        {
            var dbData = GovermentDepartmentDataService.GetDetail(db).Where(i => i.GovernmentDepartmentId == id).FirstOrDefault();
            if (dbData == null)
            {
                return RedirectToAction("Index");
            }
            InitilizeGovermentDepartment(dbData.GovernmentDepartmentId);
            return View(GovermentDepartmentMvcModel.CopyFromEntity(dbData, 0));

        }

        [HttpPost]
        public ActionResult Edit(GovermentDepartmentMvcModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var dbAdresses = GovernmentDepartmentAddressDataService.GetLite(db).ToList();
            var dbContacts = GovernmentDepartmentContactNoDataService.GetLite(db).ToList();
            var dbData = GovermentDepartmentDataService.GetDetail(db).Where(i => i.GovernmentDepartmentId == model.GovernmentDepartmentId).FirstOrDefault();
            if (dbData == null)
            {
                return RedirectToAction("Index");
            }
            if (!CommonForInsertUpdate(model))
            {
                return View(model);
            }


            dbData.Name = model.Name;
            dbData.Email = model.Email;
            dbData.Status = model.Status;
            dbData.IsDefault = model.IsDefault;
            dbData.POCName = model.POCName;
            dbData.POCContact = model.POCContact;
            dbData.ModifyBy = AppUser.UserName;
            dbData.HeadOffice = model.HeadOffice;
            // dbData.GovernmentDepartmentAddresses = new List<GovernmentDepartmentAddress>();
            // dbData.GovernmentDepartmentContactNos = new List<GovernmentDepartmentContactNo>();
            foreach (var item in model.GovernmentDepartmentContactNos)
            {
                var tempContact = dbContacts.FirstOrDefault(i => i.GovernmentDepartmentContactNoId == item.GovernmentDepartmentContactNoId);
                if (!item.DeletePhone)
                {
                    if (tempContact == null)
                    {
                        GovernmentDepartmentContactNo governmentDepartmentContactNo = new GovernmentDepartmentContactNo();
                        governmentDepartmentContactNo.GovernmentDepartmentContactNoId = Guid.NewGuid();
                        governmentDepartmentContactNo.GovernmentDepartmentId = dbData.GovernmentDepartmentId;
                        governmentDepartmentContactNo.ContactNo = item.ContactNo;
                        governmentDepartmentContactNo.ModifyBy = AppUser.UserName;
                        db.GovernmentDepartmentContactNos.Add(governmentDepartmentContactNo);
                    }
                    else
                    {
                        tempContact.ContactNo = item.ContactNo;
                        tempContact.ModifyBy = AppUser.UserName;
                    }

                }
                else
                {

                    if (tempContact != null)
                    {
                        db.GovernmentDepartmentContactNos.Remove(tempContact);
                    }


                }
            }
            foreach (var item in model.GovernmentDepartmentAddresses)
            {
                var tempAddress = dbAdresses.FirstOrDefault(i => i.GovernmentDepartmentAddressId == item.GovernmentDepartmentAddressId);
                if (!item.DeleteAddress)
                {
                    if (tempAddress == null)
                    {
                        GovernmentDepartmentAddress tempGovernmentDepartmentAddress = new GovernmentDepartmentAddress();
                        tempGovernmentDepartmentAddress.GovernmentDepartmentAddressId = Guid.NewGuid();
                        tempGovernmentDepartmentAddress.GovernmentDepartmentId = dbData.GovernmentDepartmentId;
                        tempGovernmentDepartmentAddress.Address = item.Address;
                        tempGovernmentDepartmentAddress.IsHeadOfficeAddress = item.IsHeadOfficeAddress;
                        tempGovernmentDepartmentAddress.ModifyBy = AppUser.UserName;
                        db.GovernmentDepartmentAddresses.Add(tempGovernmentDepartmentAddress);
                    }
                    else
                    {
                        tempAddress.Address = item.Address;
                        tempAddress.IsHeadOfficeAddress = item.IsHeadOfficeAddress;
                        tempAddress.ModifyBy = AppUser.UserName;
                    }
                }
                else
                {

                    if (tempAddress != null)
                    {
                        db.GovernmentDepartmentAddresses.Remove(tempAddress);
                    }
                }
            }

            db.SaveChanges();
            SucessMessage = $"Govt. Department {dbData.Name} Update sucessfully";

            return RedirectToAction("Index");
        }
        public ActionResult Details(Guid id)
        {
            var dbData = GovermentDepartmentDataService.GetDetail(db).Where(i => i.GovernmentDepartmentId == id).FirstOrDefault();
            if (dbData == null)
            {
                return RedirectToAction("Index");
            }

UPCourt.Web/Views/GovermentDepartment/Create.cshtml
@model UPCourt.Web.Models.GovermentDepartmentMvcModel
@using core.koushikiSofatware.Helper
@{
    ViewBag.Title = "Create";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Goverment Department Create</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Goverment Department Create</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- general form elements -->
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Goverment Department</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    @using (Html.BeginForm("Create", "GovermentDepartment", FormMethod.Post, new { @class = "col-md-12" }))
    {
        @Html.HiddenFor(model => model.GovernmentDepartmentId)
        @Html.AntiForgeryToken()
        @*@Html.EditorForModel("Phone", "GovernmentDepartmentContactNos",Model.GovernmentDepartmentContactNos)*@
       
            <form>
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Email", @type = "text" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                        @* <div class="form-group col-md-4">
                @Html.LabelFor(model => model.GovernmentDepartmentContactNos[0], htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.GovernmentDepartmentContactNos[0], new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Contact no", @type = "text" } })
                @Html.ValidationMessageFor(model => model.GovernmentDepartmentContactNos[0], "", new { @class = "text-danger" })
            </div>*@
                    </div>
                    <div id="Addresses">
                        <label>Addresses</label>
                        @for (int i = 0; i < Model.GovernmentDepartmentAddresses.Count; i++)
                        {
                            @Html.EditorFor(model => model.GovernmentDepartmentAddresses[i], "Address")
                        }
                    </div>
                    
                    <div class="form-group col-md-12">

                        @Html.AddLinkAddress("Add More Adresss", "#Addresses", ".Address", "GovernmentDepartmentAddresses", typeof(UPCourt.Web.Models.GovernmentDepartmentAddressMvcModel))
                    </div>
                    <br/>
                    <div id="phoneNumbers">
                        <label>Phone Numbers</label>
                        @for (int i = 0; i < Model.GovernmentDepartmentContactNos.Count; i++)
                        {
                            @Html.EditorFor(m => m.GovernmentDepartmentContactNos[i], "Phone")
                        }



                    </div>
                    
                    <div class="form-group col-md-12">
                        @Html.AddLinkPhone("Add Phone No ", "#phoneNumbers", ".phoneNumber", "GovernmentDepartmentContactNos", typeof(UPCourt.Web.Models.GovernmentDepartmentContactNoMvcModel))
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "" }) <br />
                            @Html.EnumDropDownListFor(m => m.Status, "--Select--", new
                       {
                           @class = "form-control select2",
                           @style = "width: 100%"
                       })
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            @Html.LabelFor(model => model.HeadOffice, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.HeadOffice, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter HeadOffice Name", @type = "text" } })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <div class="checkbox">

                                @Html.CheckBoxFor(model => model.IsDefault)
                                @Html.LabelFor(c => c.IsDefault, new { @class = "col-sm-2 control-label" })
                            </div>

                        </div>
                    </div>
                    @*<div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <div class="form-group">
            <label for="exampleInputFile">File input</label>
            <div class="input-group">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="exampleInputFile">
                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                </div>
                <div class="input-group-append">
                    <span class="input-group-text">Upload</span>
                </div>
            </div>
        </div>*@
                    @*<div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>*@
                </div>
                <!-- /.card-body -->
                <!-- SELECT2 EXAMPLE -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">POC Details</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            @*<button type="button" class="btn btn-tool" data-card-widget="remove">
                                    <i class="fas fa-times"></i>
                                </button>*@
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-md-6">
                                @Html.LabelFor(model => model.POCName, htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.POCName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter POC Name", @type = "text" } })
                            </div>
                            <div class="form-group col-md-6">
                                @Html.LabelFor(model => model.POCContact, htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.POCContact, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter POC Contact No", @type = "text" } })
                            </div>
                        </div>
                        <!-- /.row -->
                    </div>

                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
            }
        </div>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script type="text/javascript">
    function GetDynamicTextBox(value) {
        var row = $("<div />").attr("class", "row");

        var div = $("<div />").attr("class", "input-group");
        var divPrepend = $("<div />").attr("class", "input-group-prepend");
        var divText = $("<div />").attr("class", "input-group-text");

        var radio = $("<input />").attr("type", "radio").attr("aria-label", "Radio button for following text input").attr("name","flexRadioDefault");
        row.append(div);
        div.append(divPrepend);
        divPrepend.append(divText);
        divText.append(radio);
        var textBox = $("<input />").attr("class", "form-control").attr("type", "text").attr("aria-label", "Text input with radio button");
            textBox.val(value);
            div.append(textBox);

            var button = $("<input />").attr("type", "button").attr("value", "Remove");
            button.attr("onclick", "RemoveTextBox(this)");
        div.append(button);


            return row;
    }
    function addNestedForm(container, counter, ticks, content) {
        var nextIndex = $(counter).length;
        var pattern = new RegExp(ticks, "gi");
        content = content.replace(pattern, nextIndex);
        $(container).append(content);
    }

        @*function AddTextBox() {
            var div = GetDynamicTextBox("");
            var br = $("<div/>").attr("class","mb-2");
            $("#TextBoxContainer").append(div);
            $("#TextBoxContainer").append(br);
            }*@
           

    function RemoveTextBox(button) {
        var db = $(button).parent().parent();
        db.remove();
        //Todo Remove mb-2 class-->
        @*$(db).siblings(".mb-2").remove();*@
        }

        $(function () {
            var values = eval('@Html.Raw(ViewBag.Values)');
            if (values != null) {
                $("#TextBoxContainer").html("");
                $(values).each(function () {
                    $("#TextBoxContainer").append(GetDynamicTextBox(this));
                });
            }
        });
        
            function removeNestedForm(element, container, deleteElement) {
                $container = $(element).parents(container);
                $container.find(deleteElement).val('True');
                $container.hide();
            }

            function uncheckOther(radio) {
                var allRadioList = $(".HeadOfficeAddress");

                $.each(allRadioList, ((i, r) => {

                    if (r.id !== radio.id) {
                        $('#' + r.id).prop('checked', false)

                    }
                }))
            }
        </script>
        <!-- /.card -->

UPCourt.Web/Views/GovermentDepartment/CreateUser.cshtml
@model UPCourt.Web.Models.UserMvcModel


@using (Html.BeginForm("CreateUser", "GovermentDepartment", FormMethod.Post, new { @class = "col-md-12" }))
{
    @Html.HiddenFor(model => model.UserId)
    @Html.AntiForgeryToken()
    <div class="card card-primary">
        <!-- /.card-header -->
        <!-- form start -->
        <form>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-4">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label", @for = "exampleInputEmail1" })
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Email", @type = "email", @id = "exampleInputEmail1", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label", @for = "phoneno" })
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Contact No.", @type = "text" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label", @for = "Address" })
                        @Html.TextArea("Address", null, new { @class = "form-control", @placeholder = "Enter Address" })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        @Html.LabelFor(model => model.UserRoleId, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.UserRoleId, ViewBag.UserRoles as IEnumerable<SelectListItem>, "--Select--", new { @class = "form-control select2bs4", @required = "true", @style = "width: 100%;" })
                        @Html.ValidationMessageFor(model => model.UserRoleId, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label", @for = "password" })
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Password", @type = "password", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "" }) <br />
                        @Html.EnumDropDownListFor(m => m.Status, "--Select--", new { @class = "form-control select2", @required = "true", @style = "width: 100%" })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-4">
                        @Html.LabelFor(model => model.UserType, htmlAttributes: new { @class = "" }) <br />
                        @Html.EnumDropDownListFor(m => m.UserType, "--Select--", new { @class = "form-control select2", @required = "true", @readonly = "readonly", @style = "width: 100%" })
                        @Html.ValidationMessageFor(model => model.UserType, "", new { @class = "text-danger" })
                    </div>

                    @*<div class="form-group col-md-4">
                        @Html.LabelFor(model => model.AGDepartmentId, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.AGDepartmentId, ViewBag.AGDepartments as IEnumerable<SelectListItem>, "--Select--", new { @class = "form-control select2bs4", @style = "width: 100%;" })
                        @Html.ValidationMessageFor(model => model.AGDepartmentId, "", new { @class = "text-danger" })
                    </div>*@
                    <div class="form-group col-md-4">
                        @Html.LabelFor(model => model.GovernmentDepartmentId, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.GovernmentDepartmentId, ViewBag.GovermentDepartments as IEnumerable<SelectListItem>, "--Select--", new { @class = "form-control select2bs4", @readonly = "readonly", @style = "width: 100%;" })
                        @Html.ValidationMessageFor(model => model.GovernmentDepartmentId, "", new { @class = "text-danger" })
                    </div>
                </div>


            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}