UPCourt.Web/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UPCourt.Entity;
using UPCourt.Web.Core;
using UPCourt.Web.Models;
using UPCourt.Web.Service.DataService;

namespace UPCourt.Web.Controllers
{
    public class RegionController : BaseMVCController
    {
        // GET: Region
        public ActionResult Index()
        {
            var dbData = RegionDataService.GetLite(db).OrderBy(i => i.Name).ToList();
            return View(RegionMvcModel.CopyFromEntityList(dbData, 0));
        }

        // GET: Region/Details/5
        public ActionResult Details(Guid id)
        {
            var dbData = RegionDataService.GetLite(db).Where(i => i.RegionId == id).FirstOrDefault();
            if (dbData == null)
            {
                return RedirectToAction("Index");
            }
            return View(RegionMvcModel.CopyFromEntity(dbData, 0));
        }

        // GET: Region/Create
        public ActionResult Create()
        {
            var model = new RegionMvcModel();
            return View(model);
        }

        // POST: Region/Create
        [HttpPost]
        public ActionResult Create(RegionMvcModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (!CommonForInsertUpdate(model))
            {
                return View(model);
            }
            //if (!IsValidPermission(rModel, PageName.UserRole, PagePermissionType.CanCreate))
            //{
            //    return rModel;
            //}
            Region tempRegion = new Region();
            tempRegion.RegionId = Guid.NewGuid();
            InitializeData(tempRegion, model);

            db.Regions.Add(tempRegion);
            db.SaveChanges();
            SucessMessage = $"Region {tempRegion.Name} created sucessfully";

            return RedirectToAction("Index");
        }

        // GET: Region/Edit/5
        public ActionResult Edit(Guid id)
        {
            var dbData = RegionDataService.GetLite(db).Where(i => i.RegionId == id).FirstOrDefault();
            if (dbData == null)
            {
                return RedirectToAction("Index");
            }
            return View(RegionMvcModel.CopyFromEntity(dbData, 0));
        }

        // POST: Region/Edit/5
        [HttpPost]
        public ActionResult Edit(RegionMvcModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var dbData = RegionDataService.GetLite(db).Where(i => i.RegionId == model.RegionId).FirstOrDefault();
            if (dbData == null)
            {
                return RedirectToAction("Index");
            }
            if (!CommonForInsertUpdate(model))
            {
                return View(model);
            }
            InitializeData(dbData, model);

            db.SaveChanges();
            SucessMessage = $"Region {dbData.Name} update sucessfully";

            return RedirectToAction("Index");
        }
        private void InitializeData(Region tempRegion, RegionMvcModel model)
        {
            tempRegion.Name = model.Name;
            tempRegion.Description = model.Description;
            tempRegion.Status = model.Status;
            tempRegion.IsDefault = model.IsDefault;
            tempRegion.ModifyBy = AppUser.UserName;
        }
        private bool CommonForInsertUpdate(RegionMvcModel model)
        {
            var nameForCheck = model.Name.TrimX();
            var duplicateCheck = RegionDataService.GetLite(db).FirstOrDefault(i => i.RegionId != model.RegionId && i.Name == nameForCheck);
            if (duplicateCheck != null)
            {
                ModelState.AddModelError(nameof(model.Name), "Region name already exists");
                return false;
            }
            return true;
        }
    }
}

UPCourt.Web/Views/Region/Create.cshtml
@model UPCourt.Web.Models.RegionMvcModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Region Create</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Region Create</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- general form elements -->
@using (Html.BeginForm("Create", "Region", FormMethod.Post, new { @class = "col-md-12" }))
{
    @Html.HiddenFor(model => model.RegionId)
    @Html.AntiForgeryToken()
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Region</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Description", @type = "text" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "" }) <br />
                        @Html.EnumDropDownListFor(m => m.Status, "--Select--", new
                   {
                       @class = "form-control select2",
                       @required = "true",
                       @style = "width: 100%"
                   })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <div class="checkbox">

                            @Html.CheckBoxFor(model => model.IsDefault)
                            @Html.LabelFor(c => c.IsDefault, new { @class = "col-sm-2 control-label" })
                        </div>

                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
}
<!-- /.card -->
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}

UPCourt.Web/Views/Region/Details.cshtml
@model UPCourt.Web.Models.RegionMvcModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Region Details</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Region Details</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<!-- general form elements -->
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Region</h3>
    </div>
    <form>
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @readonly = "readonly" } })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Description", @type = "text", @readonly = "readonly" } })

                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "" }) <br />
                    @Html.EnumDropDownListFor(m => m.Status, "--Select--", new { @class = "form-control select2", @style = "width: 100%", @disabled = "disabled" })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="checkbox">
                        @Html.CheckBoxFor(model => model.IsDefault, new { @disabled = "disabled" })
                        @Html.LabelFor(c => c.IsDefault, new { @class = "col-sm-2 control-label" })
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <a href="@Url.Action("Index", "Region")" class="btn btn-primary">
                Back
            </a>
        </div>

    </form>
</div>
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}

UPCourt.Web/Views/Region/Edit.cshtml
@model UPCourt.Web.Models.RegionMvcModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Region Edit</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Region Edit</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>


@using (Html.BeginForm("Edit", "Region", FormMethod.Post, new { @class = "col-md-12" }))
{
    @Html.HiddenFor(model => model.RegionId)
    @Html.AntiForgeryToken()

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Region</h3>
        </div>

        <form>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Description", @type = "text" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "" }) <br />
                        @Html.EnumDropDownListFor(m => m.Status, "--Select--", new
                   {
                       @class = "form-control select2",
                       @required = "true",
                       @style = "width: 100%"
                   })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <div class="checkbox">

                            @Html.CheckBoxFor(model => model.IsDefault)
                            @Html.LabelFor(c => c.IsDefault, new { @class = "col-sm-2 control-label" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
}
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}

UPCourt.Web/Views/Region/Index.cshtml
@model IEnumerable<UPCourt.Web.Models.RegionMvcModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Region</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Region</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    @Html.ActionLink("Create", "Create", null, htmlAttributes: new { @class = "btn btn-block btn-success" })
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Status</th>
                            <th>Default</th>
                            <th>View</th>
                            <th>Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="tr-class-2">
                                <td>@item.Name</td>
                                <td>@item.Description</td>
                                <td>@item.Status</td>
                                <td>@item.IsDefault</td>
                                <td class="project-actions text-center">
                                    <a class="btn btn-primary btn-sm" href="@Url.Action("Details", "Region", new { id = item.RegionId })">
                                        <i class="fas fa-folder">
                                        </i>
                                        View
                                    </a>
                                </td>
                                <td>
                                    <a class="btn btn-info btn-sm" href="@Url.Action("Edit", "Region", new { id = item.RegionId })">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Edit
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/datatables/CustomDataTable.js")
    @*@Scripts.Render("~/FrontEnd/plugins/datatables/js")*@
    @*@Scripts.Render("~/Scripts/Tables/Data")*@
}